using System;
using Griffin.Decoupled.DomainEvents;

namespace Sample6.Domain.Users
{
    public class User
    {
        public User(string displayName)
        {
            if (displayName == null) throw new ArgumentNullException("displayName");
            DisplayName = displayName;
        }

        /// <summary>
        /// protected default constructor for the OR/M.
        /// </summary>
        protected User()
        {
            
        }

        /// <summary>
        /// Will be generated by the OR/M
        /// </summary>
        public int Id { get; private set; }

        /// <summary>
        /// I always use private setters on domain entities
        /// </summary>
        public string DisplayName { get; private set; }
    }
}
